// Generate hint (same as server-side)
export const generateHint = (word: string): string => {
  const hints: Record<string, string> = {
    apple: "A red or green fruit that grows on trees",
    banana: "A yellow curved fruit that monkeys love",
    car: "A vehicle with four wheels",
    dog: "A loyal pet that barks",
    elephant: "A large gray animal with a trunk",
    fish: "Lives in water and has fins",
    guitar: "A musical instrument with strings",
    house: "A place where people live",
    ice: "Frozen water",
    juice: "A drink made from fruits",
    kite: "Flies in the sky with a string",
    lion: "The king of the jungle",
    moon: "Shines in the night sky",
    nose: "You smell with this",
    orange: "A round orange fruit",
    pencil: "You write with this",
    queen: "A female ruler",
    rabbit: "A fluffy animal with long ears",
    sun: "Shines during the day",
    tree: "Has leaves and grows tall",
    umbrella: "Keeps you dry in the rain",
    violin: "A musical instrument you play with a bow",
    water: "You drink this every day",
    xylophone: "A musical instrument with colorful bars",
    yacht: "A fancy boat",
    zebra: "A black and white striped animal",
    book: "You read this",
    chair: "You sit on this",
    door: "You open this to enter a room",
    egg: "Chickens lay these",
    flower: "Beautiful and colorful, grows in gardens",
    garden: "A place where plants grow",
    hat: "You wear this on your head",
    island: "Land surrounded by water",
    jacket: "You wear this when it's cold",
    key: "You use this to unlock doors",
    lamp: "Gives light in a room",
    mouse: "A small animal that squeaks",
    nest: "Birds live here",
    ocean: "A very large body of water",
    pizza: "A round food with cheese and toppings",
    quilt: "A warm blanket",
    rocket: "Flies to space",
    star: "Shines in the night sky",
    table: "You eat meals on this",
    unicorn: "A magical horse with a horn",
    vase: "Holds flowers",
    window: "You look through this",
    "x-ray": "Doctors use this to see bones",
    yogurt: "A creamy food made from milk",
    zipper: "Opens and closes clothes",
    ball: "You play games with this",
    cat: "A furry pet that meows",
    duck: "A bird that quacks and swims",
    eye: "You see with these",
    fork: "You eat with this",
    grape: "Small round fruit, often purple or green",
    horse: "A large animal you can ride",
  };

  return (
    hints[word.toLowerCase()] ||
    `This is a common English word starting with "${word[0].toUpperCase()}".`
  );
};

